google_drive_root: "G:/My Drive/BD_satalite_thesis_data/GoogleDrive/BD_Satellite_Thesis_Data"
sentinel_drive_dir: "G:/My Drive/BD_satalite_thesis_data/GoogleDrive/BD_Satellite_Thesis_Data/raw/sentinel"
dynamic_world_drive_dir: "G:/My Drive/BD_satalite_thesis_data/GoogleDrive/BD_Satellite_Thesis_Data/raw/dynamic_world"
local_project_root: "D:/final_thesis/BD_Multimodal_Satellite_Thesis"
tabular_raw_path: "D:/final_thesis/BD_Multimodal_Satellite_Thesis/data/tabular/raw/BD_district_monthly_merged_1990_2025.csv"
metadata_dir: "D:/final_thesis/BD_Multimodal_Satellite_Thesis/data/metadata"
output_dir: "D:/final_thesis/BD_Multimodal_Satellite_Thesis/outputs"
checkpoint_dir: "D:/final_thesis/BD_Multimodal_Satellite_Thesis/checkpoints"
log_dir: "D:/final_thesis/BD_Multimodal_Satellite_Thesis/logs"
